### ISSUE TITLE
ActionDay为空字符串导致数字解析错误

### ISSUE THREAD

**Issue by kevinprotoss** [JupiterFund/postman#2]
环境：产品
错误：java.lang.NumberFormatException
分析：日期数值的分析与接受到的期望数据不匹配
错误日志：

```bash
Exception in thread "Thread-17797" java.lang.NumberFormatException: For input string: ""
        at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
        at java.lang.Integer.parseInt(Integer.java:592)
        at java.lang.Integer.parseInt(Integer.java:615)
        at com.nodeunify.jupiter.commons.mapper.qualifier.StringQualifier.parseInt(StringQualifier.java:31)
        at com.nodeunify.jupiter.commons.mapper.DatastreamMapperImpl.map(DatastreamMapperImpl.java:163)
        at com.nodeunify.jupiter.postman.source.CTPSource$MdSpiImpl.OnRtnDepthMarketData(CTPSource.java:153)
        at ctp.thostmduserapi.thostmduserapiJNI.SwigDirector_CThostFtdcMdSpi_OnRtnDepthMarketData(thostmduserapiJNI.java:9719)
```

具体代码：
[CTPSource](https://github.com/JupiterFund/postman/blob/master/src/main/java/com/nodeunify/jupiter/postman/source/CTPSource.java#L154)
[DatastreamMapper](https://github.com/JupiterFund/jupiter-commons/blob/master/src/main/java/com/nodeunify/jupiter/commons/mapper/DatastreamMapper.java#L163)
[StringQualifier](https://github.com/JupiterFund/jupiter-commons/blob/master/src/main/java/com/nodeunify/jupiter/commons/mapper/qualifier/StringQualifier.java#L31)

**Comment by kevinprotoss** [comment]
经过日志跟踪，发现实盘中的数据每天会在盘前发出一次ActionDay为空值的数据。除了UpperLimitPrice和LowerLimitPrice字段上有数值以外，其余数值皆为0。

```json
{
  "_index": "app_log-2020.03.05",
  "_type": "_doc",
  "_id": "BlsnqHABuJlzaHcqp5xz",
  "_score": null,
  "_source": {
  "message": "marketData [CThostFtdcDepthMarketDataField@290af30a InstrumentID = 'SPD MA008&MA010', ExchangeID = '', ExchangeInstID = '', ActionDay = '', TradingDay = '20200305', UpdateTime = '07:47:04', UpdateMillisec = 0, LastPrice = 1.7976931348623157E308, OpenPrice = 0.0, ClosePrice = 0.0, PreClosePrice = 0.0, HighestPrice = 0.0, LowestPrice = 0.0, AveragePrice = 0.0, Turnover = 0.0, Volume = 0, UpperLimitPrice = 150.0, LowerLimitPrice = -276.0, PreDelta = 0.0, CurrDelta = 0.0, PreOpenInterest = 0.0, OpenInterest = 0.0, PreSettlementPrice = 1.7976931348623157E308, SettlementPrice = 1.7976931348623157E308, AskPrice1 = 0.0, AskPrice2 = 0.0, AskPrice3 = 0.0, AskPrice4 = 0.0, AskPrice5 = 0.0, AskVolume1 = 0, AskVolume2 = 0, AskVolume3 = 0, AskVolume4 = 0, AskVolume5 = 0, BidPrice1 = 0.0, BidPrice2 = 0.0, BidPrice3 = 0.0, BidPrice4 = 0.0, BidPrice5 = 0.0, BidVolume1 = 0, BidVolume2 = 0, BidVolume3 = 0, BidVolume4 = 0, BidVolume5 = 0]",
    "class": "CTPSource",
    "level": "TRACE",
    "@timestamp": "2020-03-05T00:45:08.985Z",
    "@version": "1",
    "thread": "Thread-8195"
  },
  "sort": [
    1583369108985
  ]
}
```

分析：到目前为止无法理解此类数据的意图。暂时判定为无效数据，经过过滤，不作录入。

**Comment by kevinprotoss** [comment]
在实盘中发现，tradingDay字段也可能为空。

```
java.lang.NumberFormatException: For input string: ""
        at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65) ~[?:1.8.0_252]
        at java.lang.Integer.parseInt(Integer.java:592) ~[?:1.8.0_252]
        at java.lang.Integer.parseInt(Integer.java:615) ~[?:1.8.0_252]
        at com.nodeunify.jupiter.commons.mapper.qualifier.StringQualifier.parseInt(StringQualifier.java:31) ~[jupiter-commons-master-SNAPSHOT.jar!/:?]
        at com.nodeunify.jupiter.commons.mapper.DatastreamMapperImpl.map(DatastreamMapperImpl.java:172) ~[jupiter-commons-master-SNAPSHOT.jar!/:?]
        at com.nodeunify.jupiter.postman.source.CTPSource$MdSpiImpl.OnRtnDepthMarketData(CTPSource.java:184) [classes!/:?]
        at ctp.thostmduserapi.thostmduserapiJNI.SwigDirector_CThostFtdcMdSpi_OnRtnDepthMarketData(thostmduserapiJNI.java:9719) [ctpapi-v6.3.15-all.jar!/:?]
```

需要在此处进行额外的判断

https://github.com/JupiterFund/postman/blob/master/src/main/java/com/nodeunify/jupiter/postman/source/CTPSource.java#L199
